from RokuFunctions import *

def buildBurrow():
	output = createOutput("Burrow•DEV", "conspyre.tv")

	#prepareAllCategory()

	#Featured content
	loadProgramId(output, "Featured", 60320)	#featured - head 60320
	appendProgramId(output, "Featured", 58493)
	appendProgramId(output, "Featured", 61726)	#featured - tail 61726
	
	#DisclosureHub curated rows
	loadProgramId(output, "DisclosureHub Films", 59975)
	loadProgramId(output, "DisclosureHub Picks", 59976)
	loadProgramId(output, "Banned Pandemic Doctors", 59978)
	loadProgramId(output, "Lost Covid Videos", 59979)
	loadProgramId(output, "Hidden Health Wealth", 59980)	
	loadProgramId(output, "Real Law Knowledge", 59982)
	loadProgramId(output, "Quantum Human Capabilities", 59983)
	loadProgramId(output, "Human Trafficking / Elite Pedophelia", 59984)
	loadProgramId(output, "Rituals and Satanic Cults", 59985)
	loadProgramId(output, "New World Order", 59986)
	loadProgramId(output, "Free Energy", 59987)
	appendProgramId(output, "Free Energy", 60415)	#Meyer, Stanley
	appendProgramId(output, "Free Energy", 74478)	#Energy from the Vacuum
	loadProgramId(output, "EMF/EMR/RF/5G Radiation", 59988)
	loadProgramId(output, "Extraterrestrial Videos", 59989)
	loadProgramId(output, "Vaccines Exposed", 61701)

	#Just added content
	#loadProgramId(output, "Just Added", 75167)	#just added - head
	loadProgramId(output, "Conspyre•TV Latest", 58474)
	#appendProgramId(output, "Just Added", 75168)	#just added - tail

	#Alphabetical categories, documentaries, people
	loadProgramId(output, "5G", 59660)
	loadProgramId(output, "9/11", 59662)
	loadProgramId(output, "Alt. Anthropology", 61754)
	loadProgramId(output, "Antarctica", 60399)
	loadProgramId(output, "BradCGZ", 62937)
	loadProgramId(output, "CIA", 60325)
	loadProgramId(output, "Cooper, William", 59686)
	loadProgramId(output, "Cult of the Medics", 59688)
	loadProgramId(output, "Dark, The", 60328)
	loadProgramId(output, "Disclosure Library", 61762)
	loadProgramId(output, "Enthéos Shines Fan Channel", 59692)
	loadProgramId(output, "Epstein, Jeffrey", 59693)
	loadProgramId(output, "Epstein Pedo Island drone footage", 61761)
	loadProgramId(output, "Fall of the Cabal", 61751)
	loadProgramId(output, "Finders, The", 59694)
	loadProgramId(output, "Freemasons", 59695)
	loadProgramId(output, "General", 74211)
	loadProgramId(output, "Geoengineering", 59697)
	loadProgramId(output, "Giants", 59698)
	loadProgramId(output, "Great Reset", 59699)
	loadProgramId(output, "Gunderson, Ted", 59835)
	loadProgramId(output, "Health, General", 59700)
	loadProgramId(output, "Illuminati", 60402)
	loadProgramId(output, "IPOT1776", 60413)
	loadProgramId(output, "ITNJ Judicial Commission", 60403)
	loadProgramId(output, "JFK", 60405)
	loadProgramId(output, "Lazar, Bob", 60406)
	loadProgramId(output, "Lectures, Conspiracy", 74210)
	loadProgramId(output, "M3thods", 59991)
	loadProgramId(output, "Marrs, Jim", 60414)
	loadProgramId(output, "Maxwell, Jordan", 60407)
	loadProgramId(output, "Mind Control", 60416)
	loadProgramId(output, "Mouthy Buddha", 60411)
	loadProgramId(output, "MrTruthBomb", 69786)
	loadProgramId(output, "Music", 61758)
	loadProgramId(output, "NASA", 60419)
	loadProgramId(output, "ORME", 60420)
	loadProgramId(output, "Pizzagate", 60421)h
	loadProgramId(output, "Q", 61753)
	loadProgramId(output, "Remote Viewing", 60905)
	loadProgramId(output, "Schneider, Philip", 60906)
	loadProgramId(output, "Tartaria", 61755)
	loadProgramId(output, "Tyrrany & Eugenics (Jana Esp)", 61757)
	loadProgramId(output, "Thunderbolts Project", 61759)
	loadProgramId(output, "UFOs", 61763)

	writeOutput(output, "/var/www/html/AVideo/rokuv2/burrow.json")

# Do it. Build the channel.
buildBurrow()

# select videos_id from playlists_has_videos where playlists_id in (60320,58493,61726,58474,59975,59976,59978,59979,59980,59982,59983,59984,59985,59986,59987,60415,74478,59988,59989,61701,59660,59662,61754,60399,62937,60325,59686,59688,60328,61762,59692,59693,61761,61751,59694,59695,74211,59697,59698,59699,59835,59700,60402,60413,60403,60405,60406,74210,59991,60414,60407,60416,60411,69786,61758,60418,60419,60420,60421,61753,60905,60906,61755,61757,61759,61763)
	curlJsonDict(output, "5G",								"most_popular", "https://conspyre.tv/roku.json?catName=5g")
	curlJsonDict(output, "5G Crisis: Awareness & Accountability",	"most_popular", "https://conspyre.tv/roku.json?catName=5g-crisis-awareness-accountability")
	curlJsonDict(output, "9/11",							"most_popular", "https://conspyre.tv/roku.json?catName=9-11")
#	curlJsonDict(output, "Adair, David",					"most_popular",  "https://conspyre.tv/roku.json?catName=david-adair")
#	curlJsonDict(output, "Ancient Civilizations",			"most_popular",  "https://conspyre.tv/roku.json?catName=general-2")
#	curlJsonDict(output, "Bauval, Robert",					"most_popular",  "https://conspyre.tv/roku.json?catName=robert-bauval")
	curlJsonDict(output, "Bernard, Ronald",					"most_popular",  "https://conspyre.tv/roku.json?catName=ronald-bernard")
#	curlJsonDict(output, "Beyond Chemo docuseries",			"most_popular",  "https://conspyre.tv/roku.json?catName=beyond-chemo-docuseries")
#	curlJsonDict(output, "CIA",								"most_popular",  "https://conspyre.tv/roku.json?catName=general-7")
	curlJsonDict(output, "Classic Conspiracy",				"most_popular",  "https://conspyre.tv/roku.json?catName=conspyre-classic-conspiracy")
#	curlJsonDict(output, "Conquering Cancer Summit",		"most_popular",  "https://conspyre.tv/roku.json?catName=conquering-cancer-summit-2021")
#	curlJsonDict(output, "Conscious Life Expo (2020)",		"most_popular",  "https://conspyre.tv/roku.json?catName=conscious-life-expo-2020-")
	curlJsonDict(output, "Cooper, William",					"most_popular",  "https://conspyre.tv/roku.json?catName=videos")
#	curlJsonDict(output, "Coral Castle, The",				"most_popular",  "https://conspyre.tv/roku.json?catName=coral-castle")
#	curlJsonDict(output, "Crop Circles",					"most_popular",  "https://conspyre.tv/roku.json?catName=crop-circles")
	curlJsonDict(output, "Cult of the Medics",				"chronological", "https://conspyre.tv/roku.json?catName=cult-of-the-medics")
	curlJsonDict(output, "Dark, The",						"most_popular",  "https://conspyre.tv/roku.json?catName=conspyre-dark")
	curlJsonDict(output, "Disclosure Hub",					"most_popular",  "https://conspyre.tv/roku.json?catName=general-6")
#	curlJsonDict(output, "Disclosure Library",				"most_popular",  "https://conspyre.tv/roku.json?catName=disclosure-library")
	curlJsonDict(output, "Disney",							"most_popular",  "https://conspyre.tv/roku.json?catName=disney")
	curlJsonDict(output, "Documentaries",					"most_popular",  "https://conspyre.tv/roku.json?catName=conspyre-documentaries")
#	curlJsonDict(output, "Egypt",							"most_popular",  "https://conspyre.tv/roku.json?catName=egypt")
#	curlJsonDict(output, "EMF Health Summit",				"most_popular",  "https://conspyre.tv/roku.json?catName=emf-health-summit")
	curlJsonDict(output, "Enthéos Shines Fan Channel",		"most_popular",  "https://conspyre.tv/roku.json?catName=entheos-shines-fan-channel")
	curlJsonDict(output, "Epstein, Jeffrey",				"most_popular",  "https://conspyre.tv/roku.json?catName=general-8")
	curlJsonDict(output, "Fall of the Cabal",				"most_recent",   "https://conspyre.tv/roku.json?catName=fall-of-the-cabal")
	curlJsonDict(output, "Fake Election",					"most_recent",   "https://conspyre.tv/roku.json?catName=11-3-fake-election")
	curlJsonDict(output, "Finders, The",					"most_popular",  "https://conspyre.tv/roku.json?catName=the-finders")
	curlJsonDict(output, "Freemasons",						"most_popular",  "https://conspyre.tv/roku.json?catName=freemasons")
	curlJsonDict(output, "Gates, Bill",						"most_popular",  "https://conspyre.tv/roku.json?catName=bill-gates")
	curlJsonDict(output, "General",							"most_popular",  "https://conspyre.tv/roku.json?catName=conspyre-tv")
	curlJsonDict(output, "Geoengineering",					"most_popular",  "https://conspyre.tv/roku.json?catName=geoengineering")
	curlJsonDict(output, "Giants",							"most_popular",  "https://conspyre.tv/roku.json?catName=giants")
	curlJsonDict(output, "Great Reset",						"most_popular",  "https://conspyre.tv/roku.json?catName=great-reset")
#	curlJsonDict(output, "Griffin, G. Edward",				"most_popular",  "https://conspyre.tv/roku.json?catName=g-edward-griffin")
	curlJsonDict(output, "Gunderson, Ted",					"most_popular",  "https://conspyre.tv/roku.json?catName=ted-gunderson")
	curlJsonDict(output, "Hancock, Graham",					"most_popular",	 "https://conspyre.tv/roku.json?catName=graham-hancock")
	curlJsonDict(output, "Healing from GMOs",				"most_popular",  "https://conspyre.tv/roku.json?catName=healing-from-gmos")
#	curlJsonDict(output, "Health, General",					"most_popular",  "https://conspyre.tv/roku.json?catName=conspyre-health")
#	curlJsonDict(output, "Heavy Metals Summit",				"most_popular",  "https://conspyre.tv/roku.json?catName=heavy-metals-summit")
#	curlJsonDict(output, "Hoagland, Richard",				"most_popular",  "https://conspyre.tv/roku.json?catName=richard-hoagland")
#	curlJsonDict(output, "Humor",							"most_popular",  "https://conspyre.tv/roku.json?catName=humor")
#	curlJsonDict(output, "Keto Edge Summit",				"most_popular",  "https://conspyre.tv/roku.json?catName=keto-edge-summit")
	curlJsonDict(output, "Illuminati",						"most_popular",  "https://conspyre.tv/roku.json?catName=illuminati")
	curlJsonDict(output, "ITNJ Judicial Commission",		"chronological", "https://conspyre.tv/roku.json?catName=itnj-judicial-comission")
	curlJsonDict(output, "IPOT1776",						"most_popular",  "https://conspyre.tv/roku.json?catName=ipot1776")
	curlJsonDict(output, "Jacob, Frank",					"most_popular",  "https://conspyre.tv/roku.json?catName=frank-jacob")
	curlJsonDict(output, "JFK",								"most_popular",  "https://conspyre.tv/roku.json?catName=jfk")
#	curlJsonDict(output, "Live Longer Feel Better",			"most_popular",  "https://conspyre.tv/roku.json?catName=live-longer-feel-better")
	curlJsonDict(output, "Maxwell, Jordan",					"most_popular",  "https://conspyre.tv/roku.json?catName=jordan-maxwell")
	curlJsonDict(output, "Marrs, Jim",						"most_popular",  "https://conspyre.tv/roku.json?catName=jim-marrs")
	curlJsonDict(output, "Megaliths",						"most_popular",	 "https://conspyre.tv/roku.json?catName=megalithic-sites")
	curlJsonDict(output, "Meyer, Stanley",					"most_popular",  "https://conspyre.tv/roku.json?catName=stanley-meyer")
	curlJsonDict(output, "Mind Control",					"most_popular",  "https://conspyre.tv/roku.json?catName=documentary-3")
#	curlJsonDict(output, "MK-ULTRA",						"most_popular",  "https://conspyre.tv/roku.json?catName=mk-ultra")
	curlJsonDict(output, "Mouthy Buddha",					"most_popular",  "https://conspyre.tv/roku.json?catName=mouthy-buddha")
	curlJsonDict(output, "Music",							"most_popular",  "https://conspyre.tv/roku.json?catName=music")
	curlJsonDict(output, "Mystery Babylon Radio",			"chronological", "https://conspyre.tv/roku.json?catName=mystery-babylon-radio-archive")
#	curlJsonDict(output, "NASA",							"most_popular",  "https://conspyre.tv/roku.json?catName=nasa")
#	curlJsonDict(output, "ORME",							"most_popular",  "https://conspyre.tv/roku.json?catName=ormus-orme")
	curlJsonDict(output, "Pedophiles & Human Trafficking",	"most_popular",  "https://conspyre.tv/roku.json?catName=pedophiles-human-trafficking")
	curlJsonDict(output, "Pizzagate",						"most_popular",  "https://conspyre.tv/roku.json?catName=pizzagate")
	curlJsonDict(output, "Project Camelot",					"most_popular",  "https://conspyre.tv/roku.json?catName=project-camelot")
	curlJsonDict(output, "Q",								"most_popular",  "https://conspyre.tv/roku.json?catName=q")
#	curlJsonDict(output, "Remote Viewing",					"most_popular",  "https://conspyre.tv/roku.json?catName=remote-viewing")
	curlJsonDict(output, "Schneider, Philip",				"most_popular",  "https://conspyre.tv/roku.json?catName=philip-schneider")
	curlJsonDict(output, "Sepehr, Robert",					"most_popular",  "https://conspyre.tv/roku.json?catName=anthropology")
	curlJsonDict(output, "Shackleford, Rusty (Pedo Island drone footage)", "most_popular",  "https://conspyre.tv/roku.json?catName=rusty-shackleford")
	curlJsonDict(output, "Springmeier, Fritz",				"most_popular",  "https://conspyre.tv/roku.json?catName=fritz-springmeier")
	curlJsonDict(output, "SRA",								"most_popular",  "https://conspyre.tv/roku.json?catName=sra")
#	curlJsonDict(output, "Superfood Garden Summit",			"most_popular",  "https://conspyre.tv/roku.json?catName=superfood-garden-summit")
	curlJsonDict(output, "Tartaria",						"most_popular",  "https://conspyre.tv/roku.json?catName=tartaria")
	curlJsonDict(output, "Tellinger, Michael", 				"most_popular",  "https://conspyre.tv/roku.json?catName=michael-tellinger")
	curlJsonDict(output, "Tesla, Nikola",	 				"most_popular",  "https://conspyre.tv/roku.json?catName=nikola-tesla")
#	curlJsonDict(output, "Thriving Child Summit",			"most_popular",  "https://conspyre.tv/roku.json?catName=thriving-child-summit")
#	curlJsonDict(output, "Toxic Home Summit", 				"most_popular",  "https://conspyre.tv/roku.json?catName=toxic-home-summit")
	curlJsonDict(output, "Truth About Cancer, the",			"most_popular",  "https://conspyre.tv/roku.json?catName=the-truth-about-cancer" )
	curlJsonDict(output, "Tyrrany & Eugenics (Jana Esp)",	"most_recent", "https://conspyre.tv/roku.json?catName=jana-esp")
#	curlJsonDict(output, "Thunderbolts Project",			"most_popular",  "https://conspyre.tv/roku.json?catName=thunderbolts-project")
#	curlJsonDict(output, "Tsarion, Michael",				"most_popular",  "https://conspyre.tv/roku.json?catName=michael-tsarion")
	curlJsonDict(output, "UFOs",							"most_popular",  "https://conspyre.tv/roku.json?catName=lectures-1")
#	curlJsonDict(output, "West, John Anthony",				"most_popular",  "https://conspyre.tv/roku.json?catName=john-anthony-west")