from RokuFunctions import *

def buildConspyreTV():
	output = createOutput("Conspyre·TV", "conspyre.tv")

	prepareAllCategory()

	loadCategory(output, "Featured", "58493", False)						#Featured content
	loadCategory(output, "Just Added", "58493", False)

	reserveTopChronological(output, "Latest Podcasts", False)				#Alphabetical podcasters
	loadCategory(output,  "Big Dig Energy", "l", True)
	loadCategory(output,  "Brad & Abbey Show", "brad-abbey-show", True)
	loadProgramId(output, "BradCGZ", 62937, True)
	loadProgramId(output, "Disclosure Hub Hits", 59975, True)
	loadProgramId(output, "Enthéos Shines Fan Channel", 59692, False)
	loadProgramId(output, "IPOT1776", 60413, True)
	loadProgramId(output, "JustInformed Talk", 113460, True)
	loadProgramId(output, "M3thods", 59991, True)
	loadCategory(output,  "TRUreporting", "trureporting", True)

	loadProgramId(output, "Music", 61758, False)							#Music
	loadCategory(output,  "Lisa Mei Crowley", "lisa-mei-crowley", False)								
	loadProgramId(output, "Severe Anon", 103090, False)

	loadProgramId(output, "5G", 59660, False)								#Alphabetical categories
	loadProgramId(output, "9/11", 59662, False)
	loadProgramId(output, "Adair, David", 60321, False)
	loadProgramId(output, "Assange, Julian", 58473, False)
	loadProgramId(output, "Alt. Anthropology", 61754, False)
	loadProgramId(output, "Bernard, Ronald", 59685, False)
	loadProgramId(output, "Cooper, William", 59686, False)
	loadProgramId(output, "Cult of the Medics", 59688, False)
	loadCategory(output,  "Dark, The", "conspyre-dark", False)
	loadCategory(output,  "Detox Project, The", "detox-project", False)
	loadProgramId(output, "Disclosure Hub Hits", 59975, False)
	#loadCategory(output,  "Disclosure Library", "disclosure-library", False)
	loadProgramId(output, "Disney", 59689, False)
	loadProgramId(output, "Dysfunction, Election", 114334, False)
	loadCategory(output,  "Egypt", "egypt", False)
	loadProgramId(output, "Epstein, Jeffrey", 59693, False)
	loadCategory(output,  "Fall of the Cabal", "fall-of-the-cabal", False)
	loadProgramId(output, "Finders, The", 59694, False)
	loadProgramId(output, "Freemasons", 59695, False)
	loadProgramId(output, "Gates, Bill", 59696, False)
	loadCategory(output,  "General", "conspyre-tv", False)
	loadProgramId(output, "Geoengineering", 59697, False)
	loadProgramId(output, "Giants", 59698, False)
	loadProgramId(output, "Great Reset", 59699, False)
	loadProgramId(output, "Gunderson, Ted", 59835, False)
	loadCategory(output,  "Hancock, Graham", "graham-hancock", False)
	loadCategory(output,  "Healing from GMOs", "healing-from-gmos", False)
	loadProgramId(output, "Health, General", 59700, False)
	loadCategory(output,  "Illuminati",  "illuminati", False)
	loadCategory(output,  "ITNJ Judicial Commission", "itnj-judicial-comission", False)
	loadCategory(output,  "Jacob, Frank", "frank-jacob", False)
	loadCategory(output,  "JFK", "jfk", False)
	loadCategory(output,  "Lazar, Bob", "bob-lazar", False)
	loadCategory(output,  "Maxwell, Jordan", "jordan-maxwell", False)
	loadCategory(output,  "Marrs, Jim", "jim-marrs", False)
	loadCategory(output,  "Megaliths", "megalithic-sites", False)
	loadCategory(output,  "Meyer, Stanley", "stanley-meyer", False)
	loadProgramId(output, "Mind Control", 60416, False)
	loadProgramId(output, "Mouthy Buddha", 60411, False)
	loadProgramId(output, "MrTruthBomb", 69786, False)
	loadCategory(output,  "Mystery Babylon Radio", "mystery-babylon-radio-archive", False)
	loadProgramId(output, "NASA", 60419, False)
	loadProgramId(output, "ORME", 60420, False)
	loadCategory(output,  "Pizzagate", "pizzagate", False)
	loadCategory(output,  "Project Camelot", "project-camelot", False)
	loadProgramId(output, "Pizzagate", 60421, False)
	loadProgramId(output, "Remote Viewing", 60905, False)
	loadCategory(output,  "Schneider, Philip", "philip-schneider", False)
	loadCategory(output,  "Shackleford, Rusty (Pedo Island drone footage)", "rusty-shackleford", False)
	loadCategory(output,  "Springmeier, Fritz", "fritz-springmeier", False)
	loadCategory(output,  "SRA", "sra", False)
	loadProgramId(output, "Tartaria", 61755, False)
	loadCategory(output,  "Tellinger, Michael", "michael-tellinger", False)
	loadCategory(output,  "Tesla, Nikola", "nikola-tesla", False)
	loadCategory(output,  "Truth About Cancer, the", "the-truth-about-cancer" , False)
	loadProgramId(output, "TRUTHISKNOWLEDGE", 106372, False)
	loadProgramId(output, "Tyrrany & Eugenics (Jana Esp, False)", 61757, False)
	loadProgramId(output, "Thunderbolts Project", 61759, False)
	loadCategory(output,  "UFOs", "lectures-1", False)

	writeOutput(output, "/var/www/html/AVideo/rokuv2/conspyre-tv.json")

# Do it. Build the channel.
buildConspyreTV()

	#loadCategory(output, "Beyond Chemo docuseries", "beyond-chemo-docuseries", False)
	#loadCategory(output, "CIA", "general-7", False)
	#loadCategory(output, "Conquering Cancer Summit", "conquering-cancer-summit-2021", False)
	#loadCategory(output, "Conscious Life Expo (2020)", "conscious-life-expo-2020-", False)
#	loadCategory(output, "Pedophiles & Human Trafficking", "pedophiles-human-trafficking", False)
#	loadCategory(output, "Tsarion, Michael", "michael-tsarion", False)
