from RokuFunctions import *

def buildOSTO():
	output = createOutput("OSTO•Space", "truth.osto.space")
							
	loadCategory(output, "Featured", "osto-tv-content")

	#Alphabetical categories
	loadCategory(output, "OSTO TV CONTENT", "osto-tv-content")
	loadCategory(output, "1/6/2021 PRISONERS", "1-6-2021-prisoners")
	loadCategory(output, "ELECTILE DYSFUNCTION", "electile-dysfunction")
	loadCategory(output, "THE JABS", "the-jabs")
	loadCategory(output, "HUMAN TRAFFICKING", "human-trafficking")
	loadCategory(output, "THE SATANICS", "the-satanics")
	loadCategory(output, "DEEP STATE MEANS OBAMAGATE", "deep-state-means-obamagate")
	loadCategory(output, "CRYPTO-CURRENCY & (QFS)", "crypto-currency-qfs")
	loadCategory(output, "CPS-ADOPTION-FOSTER SYSTEM", "cps-adoption-foster-system")
	loadCategory(output, "ADRENOCHROME IS PEOPLE", "adrenochrome-is-people")
	loadCategory(output, "Bohemian Grove Rhapsody", "bohemian-grove-rhapsody")
	loadCategory(output, "Q", "q")
	loadCategory(output, "LINDA \"snarky\" PARIS", "linda-snarky-paris")
	loadCategory(output, "X22 REPORT", "x22-report")
	loadCategory(output, "WE THE PEOPLE (the situation)", "we-the-people-the-situtation-")
	loadCategory(output, "SANTA SURFING", "santa-surfing")
	loadCategory(output, "MITCHELL NICHOLAS GERBER", "mitchell-nicholas-gerber")
	loadCategory(output, "MELK", "melk")
	loadCategory(output, "MARTIN GEDDES", "martin-geddes")
	loadCategory(output, "THE FULFORD REPORT", "the-fulford-report")
	loadCategory(output, "STEW PETERS", "stew-peters")
	loadCategory(output, "SIMON PARKES", "simon-parkes")
	loadCategory(output, "RYUSHIN MALONE", "ryushin-malone")
	loadCategory(output, "KERRY CASSIDY", "kerry-cassidy")
	loadCategory(output, "JEAN WARDS MARS ANOMALY", "jean-wards-mars-anomaly")
	loadCategory(output, "COREYS DIGS", "coreys-digs")
	loadCategory(output, "COREY GOODE", "corey-goode")
	loadCategory(output, "\"THE SALLA\"", "-the-salla-")
	loadCategory(output, "CONSPIRACY FACT", "conspiracy-fact")
	loadCategory(output, "INTERNATIONAL TRUTH HEROES", "international-truth-hero-s")
	loadCategory(output, "NEW DIGITAL SOLDIERS", "new-digital-soldiers")
	loadCategory(output, "Lynn Miller -Intuitive Empath", "lynn-miller-intuitive-empath")
	loadCategory(output, "KNOWLEDGE OF THE FOREVER TIME", "knowledge-of-the-forever-time")
	loadCategory(output, "OSTO PAGES", "osto-pages")
	loadCategory(output, "STRANGERS IN YOUR OWN LAND", "-strangers-in-your-own-land")
	loadCategory(output, "DISCLOSURE SONGS", "disclosure-songs")
	loadCategory(output, "THE SCREAMING MEMER", "the-screaming-memer")

	writeOutput(output, "osto.json")

# Do it. Build the channel.
buildOSTO()
